apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: floatingipranges.kubefip.k8s.binbash.org
spec:
  group: kubefip.k8s.binbash.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                iprange:
                  type: string
                  pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/\d{1,2}$'
  scope: Cluster
  names:
    plural: floatingipranges
    singular: floatingiprange
    kind: FloatingIPRange
    shortNames:
      - fiprange
      - fipranges
