apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: floatingips.kubefip.k8s.binbash.org
spec:
  group: kubefip.k8s.binbash.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ipaddress: 
                  type: string
                  pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
  scope: Namespaced
  names:
    plural: floatingips
    singular: floatingip
    kind: FloatingIP
    shortNames:
      - fip
      - fips
