apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-fip-config
  namespace: {{ .Release.Namespace | default "kube-system" }}
data:
{{- if .Values.logLevel }}
  logLevel: "{{ .Values.logLevel }}"
{{- end }}
{{- if .Values.traceIpamData }}
  traceIpamData: "{{ .Values.traceIpamData }}"
{{- end }}
{{- if .Values.kubevipUpdate }}
  kubevipUpdate: "{{ .Values.kubevipUpdate }}"
{{- end }}
{{- if .Values.operateGuestClusterInterval }}
  operateGuestClusterInterval: "{{ .Values.operateGuestClusterInterval }}"
{{- end }}
{{- if .Values.kubevipGuestInstall }}
  kubevipGuestInstall: "{{ .Values.kubevipGuestInstall }}"
{{- end }}
{{- if .Values.kubevipNamespace }}
  kubevipNamespace: "{{ .Values.kubevipNamespace }}"
{{- end }}
{{- if .Values.kubevipChartRepoUrl }}
  kubevipChartRepoUrl: "{{ .Values.kubevipChartRepoUrl }}"
{{- end }}
{{- if .Values.kubevipChartValues }}
  kubevipChartValues: |
    config:
      vip_interface: {{ .Values.kubevipChartValues.config.vip_interface | default "enp1s0" }}
    image:
      repository: {{ .Values.kubevipChartValues.image.repository | default "plndr/kube-vip" }}
      tag: {{ .Values.kubevipChartValues.image.tag | default "v0.4.1" }}
    nodeSelector:
      {{ .Values.kubevipChartValues.nodeSelector | default "node-role.kubernetes.io/master: 'true'" }}
  kubevipCloudProviderChartValues: |
    image:
      repository: {{ .Values.kubevipCloudProviderChartValues.image.repository | default "kubevip/kube-vip-cloud-provider" }}
      tag: {{ .Values.kubevipCloudProviderChartValues.image.tag | default "0.1" }}
{{- end }}
{{- if .Values.removeHarvesterCloudProvider }}
  removeHarvesterCloudProvider: "{{ .Values.removeHarvesterCloudProvider }}"
{{- end }}
{{- if .Values.harvesterCloudProviderNamespace }}
  harvesterCloudProviderNamespace: "{{ .Values.harvesterCloudProviderNamespace }}"
{{- end }}
