apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-fip-config
  namespace: {{ .Release.Namespace | default "kube-system" }}
data:
  logLevel: "Info"
  traceIpamData: "false"
  kubevipUpdate: "false"
  operateGuestClusterInterval: "480"
  kubevipGuestInstall: "clusterlabel"
  kubevipNamespace: kube-system
  kubevipChartRepoUrl: {{ .Values.kubevipChartRepoUrl | default "https://kube-vip.io/helm-charts" }}
  kubevipChartValues: |
    config:
      vip_interface: {{ .Values.kubevipChartValues.config.vip_interface | default "enp1s0" }}
    image:
      repository: {{ .Values.kubevipChartValues.image.repository | default "plndr/kube-vip" }}
      tag: {{ .Values.kubevipChartValues.image.tag | default "v0.3.7" }}
    nodeSelector:
      {{ .Values.kubevipChartValues.nodeSelector | default "node-role.kubernetes.io/master: 'true'" }}
  kubevipCloudProviderChartValues: |
    image:
      repository: {{ .Values.kubevipCloudProviderChartValues.image.repository | default "kubevip/kube-vip-cloud-provider" }}
      tag: {{ .Values.kubevipCloudProviderChartValues.image.tag | default "0.1" }}
  removeHarvesterCloudProvider: "false"
  harvesterCloudProviderNamespace: "kube-system"
