{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ include "kube-fip-operator.fullname" . }}-kubeconfig-read
  namespace: fleet-default
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-fip-operator.fullname" . }}-kubeconfig-read
subjects:
- kind: ServiceAccount
  name: {{ include "kube-fip-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-fip-operator.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-fip-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-fip-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
{{- end }}
