apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-fip-operator.fullname" . }}-kubeconfig-read
  namespace: fleet-default
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-fip-operator.fullname" . }}-clusterid-read
  namespace: cattle-global-data
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-fip-operator.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
    - get
    - list
