apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-fip-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kube-fip-operator.selectorLabels" . | nindent 8 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      protocol: TCP
      targetPort: {{ .Values.metricsPort }}
  sessionAffinity: None
  type: ClusterIP
