{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-fip-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-fip-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
